name: on_space
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  google_maps_flutter: ^2.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  page_transition: ^2.1.0
  timeago: ^3.6.0
  cached_network_image: ^3.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/style/
    - assets/images/
