name: on_space

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - user_cubit
  pull_request:
    branches:
      - user_cubit

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
    steps:
    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze .
    - run: flutter build apk
      uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
